---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-app-secret
  namespace: app
spec:
  encryptedData:
    api-key: AgCvKtu0qhGGVWAB1BZ91DUbThvTEUj2fjG9cC+AQrEmcfmmeo98wuaeFibE8z4sTgkFtwQ9boQrGNmZ8LqwqflnSScaLZ4OR+boeX/kh5bgtE+qJZ3XSTeEJF0l7xDARvn+2F1wJMEX7AICdjp6m498IADCShqeesFoVIpSBYciJdeT4QjJH6q9Ox515W3J8xVogZJA1yZSR3ZuGszJViMbxra5n5VlrGWKabIErfcyjSvECuHYtf7d3wQaViGihHqpOVHbTCMD1O03ZjYqKG/jbq3k/S+57NSRbrf8B/NIo+zNWzz4eniaf5wJH/ZPe/27wY1zsVzabqH2xs17LUsybLxPI18loM9j4ZIxHOopo5G1slldX5nerxMZM0LZWGII3lKYUBYeSgtrkJrCJBI/Y4B4wwtObOxLHd76QIud5zQJFOCOpu5rbh4HuNV/HVuogrvi65EdXkrzrBcOq7QOkgX8GMus79+o4+z0kH/sxxjCvEZ65S0llAWdfiHBlDJJwk1dPurgLDaa0BjahQTPwGVCgPlCK36I75Fas3YDW69kMCAL2Y7BcDr9xENyNicYviF5r0xVasWGipojmMoBFtBhS/rELBTJM4RsLeQcecoZKrlNBwGhZs9hvtX/NuG5lyo5s+dK+EAbI3Mj0h9CFuTdQYdZ/z2qQ1asiXokrlglMKMpL6+DA60Q21jDcbvBZD95QxZRODU2kLQmhQXSqNJUmuxHdCTJ8jpp58Q=
  template:
    metadata:
      name: sample-app-secret
      namespace: app
