apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-templates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/soodrajesh/minikube-gitops-platform.git
    targetRevision: main
    path: gitops/policies/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
